[package]
name = "libaeron-sys"
version = "1.0.0+1.28.0"
authors = ["Bradlee Speice <bradlee@speice.io>"]
edition = "2018"

[dependencies]

[build-dependencies]
bindgen = "0.54"
cmake = "0.1"
dunce = "1.0"

[features]
static = []

[badges]
travis-ci = "bspeice/libaeron-sys"