name: CI

on:
  push:
    branches: [master, staging, trying]
  pull_request:
    branches: [master]

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        features: [default]
        rust-version: ["stable"]

    env:
      feature-flags: ${{ matrix.features != 'default' && format('--features {0}', matrix.features) || '' }}

    steps:
      - name: Where
        run: get-command echo

      - name: Where CMake
        run: get-command cmake

      - name: Try
        run: cmake -E env echo "Hello"

      - name: Env
        run: cmake -E environment

      - name: Cmd
        run: get-command

      - name: Env
        run: cmake -E env where echo

